name: Build Client

on:
  push:
    tags:
      - '*'
jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Build
        run: |
          cd client
          go mod download
          go build -ldflags "-s -w -extldflags '-static'" -o message-receiver.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            client/message-receiver.exe
            client/starter.vbs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}